// Government schemes farmers in Telangana can benefit from. Sourced + verified via
// docs/schemes-research.md (2024–mid-2026). HONESTY RULES baked in:
//   - No hard-coded rupee figure unless an official source confirms the CURRENT number;
//     otherwise the copy says "verify on the official portal".
//   - `status` lets the app show the truth (active / verify-this-season / at-risk /
//     closed / suspended) instead of silently omitting a scheme a farmer knows by name.
//   - `honesty_note` surfaces who commonly MISSES a benefit (tenant / forest-land farmers).
//   - "Rythu Bandhu" is retired — the live scheme is "Rythu Bharosa" (relaunched Jan 2025).

export type SchemeStatus = "active" | "verify" | "at_risk" | "closed" | "suspended";
export type SchemeLevel = "central" | "state";

export interface Scheme {
  key: string;
  level: SchemeLevel;
  status: SchemeStatus;
  priority: number; // 1–5, higher shows first
  name_te: string;
  name_en: string;
  what_te: string;
  what_en: string;
  who_te: string;
  who_en: string;
  how_te: string;
  how_en: string;
  honesty_te?: string;
  honesty_en?: string;
  url: string;
  status_as_of?: string;
}

export const SCHEMES: readonly Scheme[] = [
  // ─── Telangana state ───────────────────────────────────────────────
  {
    key: "rythu_bharosa",
    level: "state",
    status: "active",
    priority: 5,
    name_te: "రైతు భరోసా",
    name_en: "Rythu Bharosa",
    what_te: "పంట పెట్టుబడి సాయం (2025లో పునఃప్రారంభం). మొదటి ఎకరానికి ప్రాధాన్యం, దశలవారీగా.",
    what_en: "Crop investment support (relaunched 2025). First-acre priority, phased.",
    who_te: "భూ భారతిలో నమోదైన సాగు భూమి ఉన్న రైతులు.",
    who_en: "Farmers with land recorded in Bhu Bharathi.",
    how_te: "మీ గ్రామ AEO / రైతు వేదిక ద్వారా వివరాలు తెలుసుకోండి.",
    how_en: "Check via your village AEO / Rythu Vedika.",
    honesty_te: "కౌలుదారులు, పట్టా లేని రైతులు చాలావరకు అర్హులు కాదు. ప్రస్తుత మొత్తాన్ని పోర్టల్‌లో చూడండి.",
    honesty_en: "Tenant & patta-less farmers are usually not eligible. Check the current amount on the portal.",
    url: "https://rythubharosa.telangana.gov.in/",
    status_as_of: "2026-07",
  },
  {
    key: "rythu_bima",
    level: "state",
    status: "active",
    priority: 5,
    name_te: "రైతు బీమా",
    name_en: "Rythu Bima (life insurance)",
    what_te: "రైతు మరణిస్తే కుటుంబానికి జీవిత బీమా పరిహారం — ఉచితం (ప్రభుత్వమే ప్రీమియం కడుతుంది).",
    what_en: "Life-insurance payout to the family if a farmer dies — free (state pays the premium).",
    who_te: "నమోదైన సాగు భూమి ఉన్న రైతులు (వయో పరిమితి వర్తిస్తుంది).",
    who_en: "Enrolled land-owning farmers (age limits apply).",
    how_te: "నమోదు కోసం మీ AEO / రైతు వేదికను సంప్రదించండి.",
    how_en: "Enrol via your AEO / Rythu Vedika.",
    honesty_te: "భూమి పట్టాతో ముడిపడి ఉంది — కౌలుదారులు అర్హులు కాకపోవచ్చు. నమోదు గడువులు గమనించండి.",
    honesty_en: "Tied to land title — tenants may not qualify. Watch enrolment windows.",
    url: "https://www.myscheme.gov.in/schemes/rythu-bima",
    status_as_of: "2026-07",
  },
  {
    key: "free_ag_power",
    level: "state",
    status: "active",
    priority: 4,
    name_te: "ఉచిత వ్యవసాయ విద్యుత్",
    name_en: "Free agricultural power",
    what_te: "వ్యవసాయ పంపుసెట్లకు 24 గంటల ఉచిత విద్యుత్.",
    what_en: "24-hour free electricity for farm pumpsets.",
    who_te: "వ్యవసాయ విద్యుత్ కనెక్షన్ ఉన్న రైతులు.",
    who_en: "Farmers with an agricultural power connection.",
    how_te: "మీ స్థానిక విద్యుత్ శాఖ / DISCOM కార్యాలయాన్ని సంప్రదించండి.",
    how_en: "Contact your local electricity (DISCOM) office.",
    url: "https://tgsouthernpower.org/",
    status_as_of: "2026-07",
  },
  {
    key: "indiramma_atmiya_bharosa",
    level: "state",
    status: "verify",
    priority: 4,
    name_te: "ఇందిరమ్మ ఆత్మీయ భరోసా",
    name_en: "Indiramma Atmiya Bharosa",
    what_te: "భూమి లేని వ్యవసాయ కూలీలకు ఏటా సాయం — రైతు భరోసా అందని వారికి.",
    what_en: "Yearly support for landless farm labourers — for those who don't get Rythu Bharosa.",
    who_te: "భూమి లేని వ్యవసాయ కూలీ కుటుంబాలు.",
    who_en: "Landless agricultural-labour families.",
    how_te: "గ్రామ సభ / AEO ద్వారా అర్హత తెలుసుకోండి.",
    how_en: "Check eligibility via Gram Sabha / AEO.",
    honesty_te: "ఆ ఏడాది కనీసం 20 రోజులు ఉపాధి హామీ (MGNREGS) పని చేసి ఉండాలి — చాలామంది ఇక్కడే అనర్హులవుతారు.",
    honesty_en: "Needs ≥20 days of MGNREGS work that year — many miss out on this condition.",
    url: "https://www.telangana.gov.in/",
    status_as_of: "2026-07",
  },
  {
    key: "paddy_bonus",
    level: "state",
    status: "at_risk",
    priority: 3,
    name_te: "సన్న వరి బోనస్",
    name_en: "Fine-rice (paddy) bonus",
    what_te: "సన్న రకం వరి పండించే రైతులకు క్వింటాల్‌కు అదనపు బోనస్.",
    what_en: "Extra bonus per quintal for farmers growing fine-variety paddy.",
    who_te: "నోటిఫై చేసిన సన్న వరి రకాలు పండించి, కొనుగోలు కేంద్రంలో అమ్మిన రైతులు.",
    who_en: "Farmers growing notified fine paddy and selling at a procurement centre.",
    how_te: "IKP / PACS కొనుగోలు కేంద్రంలో అమ్మేటప్పుడు నమోదు చేసుకోండి.",
    how_en: "Register when selling at an IKP / PACS procurement centre.",
    honesty_te: "ఈ బోనస్ ప్రతి సీజన్‌లో ఉండకపోవచ్చు — ఈ సీజన్‌లో అమల్లో ఉందో లేదో నిర్ధారించుకోండి.",
    honesty_en: "This bonus may not run every season — confirm it's active this season.",
    url: "https://civilsupplies.telangana.gov.in/",
    status_as_of: "2026-07",
  },
  {
    key: "tseed",
    level: "state",
    status: "active",
    priority: 3,
    name_te: "సబ్సిడీ విత్తనాలు (T-SEED)",
    name_en: "Subsidised seed (T-SEED)",
    what_te: "తక్కువ ధరకు నాణ్యమైన విత్తనాలు — సీజన్‌కు ముందు.",
    what_en: "Quality seed at a subsidised price, ahead of the season.",
    who_te: "పాస్‌బుక్ ఉన్న రైతులు.",
    who_en: "Farmers with a land passbook.",
    how_te: "పాస్‌బుక్ + ఆధార్‌తో మండల విత్తన విక్రయ కేంద్రానికి వెళ్లండి.",
    how_en: "Go to the mandal seed sale point with your passbook + Aadhaar.",
    url: "https://kisan.telangana.gov.in/",
    status_as_of: "2026-07",
  },
  {
    key: "podu_rofr",
    level: "state",
    status: "verify",
    priority: 2,
    name_te: "పోడు / అటవీ భూమి పట్టాలు (ROFR)",
    name_en: "Podu / forest-land pattas (ROFR)",
    what_te: "అటవీ భూమి సాగు చేసే గిరిజన రైతులకు హక్కు పత్రం (పట్టా).",
    what_en: "Land-right title (patta) for tribal farmers cultivating forest land.",
    who_te: "అటవీ హక్కుల చట్టం కింద అర్హులైన గిరిజన / అటవీ-సమీప రైతులు.",
    who_en: "Tribal / forest-fringe farmers eligible under the Forest Rights Act.",
    how_te: "ITDA / గిరిజన సంక్షేమ శాఖను సంప్రదించండి.",
    how_en: "Contact ITDA / Tribal Welfare Department.",
    honesty_te: "ప్రస్తుతం కొత్త దరఖాస్తుల రౌండ్ నిర్ధారించబడలేదు — 'ఇప్పుడు దరఖాస్తు చేయండి' అని కాదు, ముందు ఆరా తీయండి.",
    honesty_en: "No confirmed new application round right now — check first, don't assume you can apply now.",
    url: "https://tribal.telangana.gov.in/",
    status_as_of: "2026-07",
  },
  {
    key: "crop_loan_waiver",
    level: "state",
    status: "closed",
    priority: 1,
    name_te: "పంట రుణ మాఫీ (2024)",
    name_en: "Crop loan waiver (2024)",
    what_te: "2024లో ఒకసారి చేసిన పంట రుణ మాఫీ.",
    what_en: "A one-time crop-loan waiver done in 2024.",
    who_te: "అర్హత గల పంట రుణాలు తీసుకున్న రైతులు (ఆ నాటికి).",
    who_en: "Farmers with eligible crop loans (as of then).",
    how_te: "కొత్త దరఖాస్తు లేదు — మీ ఖాతాకు జమ అయిందో లేదో బ్యాంకులో చూసుకోండి.",
    how_en: "No new application — check with your bank whether it was credited.",
    url: "https://clw.telangana.gov.in/",
    status_as_of: "2026-07",
  },
  {
    key: "sheep_distribution",
    level: "state",
    status: "suspended",
    priority: 1,
    name_te: "గొర్రెల పంపిణీ",
    name_en: "Sheep distribution",
    what_te: "సబ్సిడీపై గొర్రెల యూనిట్ల పంపిణీ పథకం.",
    what_en: "Subsidised sheep-unit distribution scheme.",
    who_te: "గొర్రెల కాపరుల సొసైటీ సభ్యులు.",
    who_en: "Members of shepherd cooperative societies.",
    how_te: "ప్రస్తుతం నిలిపివేయబడింది — దరఖాస్తు చేయవద్దు; అప్‌డేట్ కోసం వేచి ఉండండి.",
    how_en: "Currently suspended — do not apply; wait for an update.",
    url: "https://ossds.telangana.gov.in/",
    status_as_of: "2026-07",
  },

  // ─── Central ───────────────────────────────────────────────────────
  {
    key: "pm_kisan",
    level: "central",
    status: "active",
    priority: 5,
    name_te: "పీఎం-కిసాన్",
    name_en: "PM-KISAN",
    what_te: "కేంద్రం నుంచి ఏటా ₹6,000 (₹2,000 చొప్పున 3 విడతలు) నేరుగా ఖాతాలో.",
    what_en: "₹6,000/year from the centre (3 × ₹2,000) straight to your bank.",
    who_te: "భూమి ఉన్న చిన్న, సన్నకారు రైతు కుటుంబాలు.",
    who_en: "Small & marginal land-holding farmer families.",
    how_te: "pmkisan.gov.in → Farmers Corner, లేదా CSC / AEO. హెల్ప్‌లైన్ 155261.",
    how_en: "pmkisan.gov.in → Farmers Corner, or CSC / AEO. Helpline 155261.",
    honesty_te: "e-KYC + ఆధార్-బ్యాంక్ లింక్ తప్పనిసరి — లేకపోతే డబ్బు ఆగిపోతుంది. 'Know Your Status'లో చూసుకోండి.",
    honesty_en: "e-KYC + Aadhaar-bank link are mandatory — else payment stops. Check 'Know Your Status'.",
    url: "https://pmkisan.gov.in",
    status_as_of: "2026-07",
  },
  {
    key: "pmfby",
    level: "central",
    status: "verify",
    priority: 5,
    name_te: "పంట బీమా (PMFBY)",
    name_en: "Crop Insurance (PMFBY)",
    what_te: "వర్షాభావం, వరదలు, తెగుళ్ల వల్ల పంట నష్టపోతే బీమా పరిహారం.",
    what_en: "Insurance payout if your crop fails due to drought, flood, or pests.",
    who_te: "ఆ సీజన్‌లో నోటిఫై చేసిన పంటలు, నోటిఫై చేసిన ప్రాంతంలో సాగు చేసే రైతులు.",
    who_en: "Farmers growing notified crops in notified areas that season.",
    how_te: "గడువులోగా బ్యాంక్ / CSC / pmfby.gov.in ద్వారా నమోదు చేసుకోండి.",
    how_en: "Enrol before the cut-off via bank / CSC / pmfby.gov.in.",
    honesty_te: "'మీకు బీమా ఉంది' అని అనుకోవద్దు — ఈ సీజన్ జిల్లా నోటిఫికేషన్‌ను AEOతో నిర్ధారించుకోండి.",
    honesty_en: "Don't assume you're covered — confirm this season's district notification with the AEO.",
    url: "https://pmfby.gov.in",
    status_as_of: "2026-07",
  },
  {
    key: "kcc",
    level: "central",
    status: "active",
    priority: 5,
    name_te: "కిసాన్ క్రెడిట్ కార్డు (KCC)",
    name_en: "Kisan Credit Card (KCC)",
    what_te: "తక్కువ వడ్డీకి పంట రుణం — సకాలంలో చెల్లిస్తే వడ్డీ దాదాపు 4%.",
    what_en: "Low-interest crop loan — about 4% effective if repaid on time.",
    who_te: "రైతులు, కౌలుదారులు, భాగస్వామ్య రైతులు.",
    who_en: "Farmers, tenant farmers & sharecroppers.",
    how_te: "బ్యాంక్ శాఖ / JanSamarth పోర్టల్. PM-KISAN రైతులకు సులభ దరఖాస్తు.",
    how_en: "Bank branch / JanSamarth portal. Simplified form for PM-KISAN beneficiaries.",
    honesty_te: "₹2 లక్షల వరకు హామీ (collateral) అవసరం లేదు. మీ బ్యాంక్ వర్తించే పరిమితిని నిర్ధారించుకోండి.",
    honesty_en: "Collateral-free up to ₹2 lakh. Confirm the ceiling your bank applies.",
    url: "https://www.myscheme.gov.in/schemes/kcc",
    status_as_of: "2026-07",
  },
  {
    key: "soil_health",
    level: "central",
    status: "active",
    priority: 4,
    name_te: "భూసార కార్డు",
    name_en: "Soil Health Card",
    what_te: "మీ నేలలో పోషకాలు, ఎంత ఎరువు వాడాలో తెలిపే ఉచిత కార్డు — ఖర్చు తగ్గుతుంది.",
    what_en: "A free card showing your soil's nutrients and how much fertiliser to use — cuts costs.",
    who_te: "ఏ రైతైనా — నమూనా ఇచ్చి పొందవచ్చు.",
    who_en: "Any farmer — get it by submitting a soil sample.",
    how_te: "AEO / KVK / మట్టి పరీక్ష కేంద్రం ద్వారా నమూనా ఇవ్వండి.",
    how_en: "Submit a sample via your AEO / KVK / soil-testing lab.",
    url: "https://www.soilhealth.dac.gov.in",
    status_as_of: "2026-07",
  },
  {
    key: "pmksy_pdmc",
    level: "central",
    status: "verify",
    priority: 4,
    name_te: "సూక్ష్మ నీటిపారుదల (డ్రిప్/స్ప్రింక్లర్)",
    name_en: "Micro-irrigation (drip / sprinkler)",
    what_te: "డ్రిప్ / స్ప్రింక్లర్ ఏర్పాటుకు సబ్సిడీ — నీరు, ఖర్చు ఆదా.",
    what_en: "Subsidy for drip / sprinkler systems — saves water and cost.",
    who_te: "భూమి ఉన్న / కౌలు రైతులు; చిన్న, సన్నకారు రైతులకు ప్రాధాన్యం.",
    who_en: "Land-owning / lessee farmers; priority to small & marginal.",
    how_te: "వ్యవసాయ / ఉద్యానవన శాఖ లేదా KVK ద్వారా దరఖాస్తు చేయండి.",
    how_en: "Apply via the Agriculture / Horticulture Department or KVK.",
    honesty_te: "సబ్సిడీ శాతం రాష్ట్రం, పంటను బట్టి మారుతుంది — ప్రస్తుత తెలంగాణ శాతాన్ని నిర్ధారించుకోండి.",
    honesty_en: "Subsidy % varies by state & crop — confirm the current Telangana figure.",
    url: "https://pmksy.gov.in",
    status_as_of: "2026-07",
  },
  {
    key: "pm_kmy",
    level: "central",
    status: "active",
    priority: 3,
    name_te: "రైతు పింఛను (PM-KMY)",
    name_en: "Farmer pension (PM-KMY)",
    what_te: "60 ఏళ్ల తర్వాత నెలకు ₹3,000 పింఛను.",
    what_en: "₹3,000/month pension after age 60.",
    who_te: "18–40 ఏళ్ల చిన్న, సన్నకారు రైతులు (2 హెక్టార్ల లోపు).",
    who_en: "Small & marginal farmers aged 18–40 (up to 2 ha).",
    how_te: "CSC / పోర్టల్‌లో ఆధార్ + ఆటో-డెబిట్‌తో నమోదు. హెల్ప్‌లైన్ 1800-3000-3468.",
    how_en: "Enrol via CSC / portal with Aadhaar + auto-debit. Helpline 1800-3000-3468.",
    honesty_te: "నెలవారీ చిన్న మొత్తం మీరు కట్టాలి (వయసును బట్టి) — ప్రభుత్వం సరిసమానంగా కలుపుతుంది.",
    honesty_en: "You pay a small monthly amount (by entry age) — the govt matches it.",
    url: "https://pmkmy.gov.in",
    status_as_of: "2026-07",
  },
  {
    key: "smam",
    level: "central",
    status: "active",
    priority: 3,
    name_te: "వ్యవసాయ యంత్రీకరణ (SMAM)",
    name_en: "Farm mechanisation (SMAM)",
    what_te: "ట్రాక్టర్లు, పరికరాలపై సబ్సిడీ; అద్దెకు యంత్రాల కేంద్రాలు (CHC).",
    what_en: "Subsidy on machines/tools; custom-hiring centres (CHCs) to rent equipment.",
    who_te: "రైతులు (చిన్న/సన్నకారు, మహిళలు, SC/STకు ఎక్కువ సబ్సిడీ), SHGలు, FPOలు.",
    who_en: "Farmers (higher subsidy for small/marginal, women, SC/ST), SHGs, FPOs.",
    how_te: "తెలంగాణ వ్యవసాయ పోర్టల్ (agrimachinery.nic.in) ద్వారా దరఖాస్తు.",
    how_en: "Apply via the Telangana agri portal (agrimachinery.nic.in).",
    honesty_te: "దరఖాస్తు విండోలు అప్పుడప్పుడే తెరుస్తారు — కొనకుండా అద్దెకు (CHC) తీసుకోవడం చిన్న రైతులకు మేలు.",
    honesty_en: "Application windows open periodically — renting via a CHC (not buying) suits small farmers.",
    url: "https://agrimachinery.nic.in",
    status_as_of: "2026-07",
  },
  {
    key: "enam",
    level: "central",
    status: "active",
    priority: 3,
    name_te: "ఈ-నామ్ (జాతీయ మార్కెట్)",
    name_en: "e-NAM (national market)",
    what_te: "ఆన్‌లైన్ మార్కెట్ — మంచి ధర, నేరుగా ఖాతాకు చెల్లింపు, దళారుల ఆధారం తగ్గుతుంది.",
    what_en: "Online market — fairer price, payment straight to your account, less middleman dependence.",
    who_te: "అనుసంధానిత మార్కెట్ (APMC)లో నమోదైన రైతులు.",
    who_en: "Farmers registered at a linked APMC mandi.",
    how_te: "enam.gov.in / e-NAM యాప్‌లో 'Farmer'గా నమోదు చేసుకోండి.",
    how_en: "Register as a 'Farmer' on enam.gov.in / the e-NAM app.",
    honesty_te: "మీ దగ్గరి మార్కెట్ ఈ-నామ్‌లో ఉందో లేదో నిర్ధారించుకోండి. నగదు గ్రాంట్ కాదు.",
    honesty_en: "Confirm a nearby mandi is on e-NAM. This is not a cash grant.",
    url: "https://enam.gov.in",
    status_as_of: "2026-07",
  },
  {
    key: "pm_kusum",
    level: "central",
    status: "verify",
    priority: 3,
    name_te: "సౌర పంపుసెట్లు (PM-KUSUM)",
    name_en: "Solar pumps (PM-KUSUM)",
    what_te: "సబ్సిడీపై సౌర విద్యుత్ పంపుసెట్లు — డీజిల్/కరెంటు ఖర్చు తగ్గుతుంది.",
    what_en: "Subsidised solar pumpsets — cuts diesel / power cost.",
    who_te: "వ్యక్తిగత రైతులు, రైతు గ్రూపులు, FPOలు.",
    who_en: "Individual farmers, farmer groups, FPOs.",
    how_te: "తెలంగాణ రాష్ట్ర పోర్టల్ (TGREDCO) ద్వారా దరఖాస్తు. హెల్ప్‌లైన్ 1800-180-3333.",
    how_en: "Apply via the Telangana state portal (TGREDCO). Helpline 1800-180-3333.",
    honesty_te: "⚠️ నమోదు రుసుము లేదు — 'application fee' అడిగే సైట్‌లు మోసం. ప్రస్తుత సబ్సిడీ శాతం నిర్ధారించుకోండి.",
    honesty_en: "⚠️ No registration fee — sites asking an 'application fee' are scams. Confirm the current subsidy split.",
    url: "https://pmkusum.telangana.gov.in/",
    status_as_of: "2026-07",
  },
];
